* Implements automatic backup:   * if hostname and remote-path are given, the backup will be stored there automaticly * some improvements in code for better readability

diff --git a/autoupdate b/autoupdate
--- a/autoupdate
+++ b/autoupdate
@@ -4,15 +4,37 @@
 # Config
 #
 
+#This section defines several values for automatic backup. Does not need to be adjusted, if you will not use backup-function
+CLIENT_NAME="complete-hostname"
+CLIENT_USER="user"
+CLIENT_PATH="/complete/path/to/your/backups/"
+
+### don not edit! ###
 PATH_BIN="/tmp/sysupgrade.bin"
 PATH_JSON="/tmp/router.json"
+PATH_BAK="/tmp/backup.tar.gz"
 JSON_LINK="https://cloud.pcfw.eu/index.php/s/ByFDyyZ2oNBY7we/download"
 LOG_FILE="/root/autoupgrade.log"
+
+
+
+#do backup
+read -p "Do you want to do a backup? (y/n)" BACKUP
+if [ $BACKUP = "y" ]; then
+  TODAY=$(date -u +%Y-%m-%d)
+  HOSTNAME=$(uci -q get system.@system[0].hostname)
+  sysupgrade -b "$PATH_BAK"
+  scp "$PATH_BAK" "$CLIENT_USER""@$CLIENT_NAME"":$CLIENT_PATH""$TODAY""_$HOSTNAME"".tar.gz"
+elif [ $BACKUP != "y" -a $BACKUP != "n" ]; then
+  echo "Error: Input is neither 'y' nor 'n'"
+  echo "Please restart the script..."
+  exit 1
+fi
 
 #get router model
 ROUTER=$(grep machine /proc/cpuinfo | cut -c 21-)
 
-#get uplinktype. Tunneldigger router get a ip-adress from 172.31.230.111/20 on ffuplink
+#get uplinktype. Tunneldigger router get an ip-adress from 172.31.230.111/20 on ffuplink
 A=$(ip addr show ffuplink | grep "172.31.230.111")
 if [ -n "$A" ]; then
   TYPE="tunneldigger"
@@ -58,7 +80,7 @@ if [ $JDATE -ge $LST_UPGRADE ]; then
   read -p "Please confirm the upgrade by typing 'yes': " B
   if [ "$B" != "yes" ];then
     echo ""
-    echo "Input is not 'yes'."
+    echo "Error: Input is not 'yes'."
     echo "You may upgrade your Router manually using:"
     echo ""
     echo "sysupgrade $PATH_BIN"
