* rework remote-backup-function * add prompt to sendstring function

diff --git a/files/autoupdate b/files/autoupdate
--- a/files/autoupdate
+++ b/files/autoupdate
@@ -80,7 +80,13 @@ get_router () {
 commit_routerstring () {
   get_router
   ROUTER2=$(echo "$ROUTER" | sed -f /usr/share/autoupdate/urlencode.sed)
-  wget "$DOMAIN/devicename;$ROUTER2;"
+  wget "$DOMAIN/devicename;$ROUTER2;" >> /dev/null
+  #we 'send' the string into the webservers log and can grab them from there via a script. Server will normally give HTTP error 404.
+  if [ $? == 8 ]; then
+    echo "String submitted successfully."
+  else
+    echo "An error occured while submitting the string. Is there a way to the internet?"
+  fi
 }
 
 #determine the current firmware-type (tunnel/no-tunnel, etc)
@@ -102,6 +108,13 @@ do_backup () {
 }
 
 remote_backup () {
+  if [ "$CLIENT_NAME" = "complete-hostname" ] && [ "$CLIENT_USER" = "user" ] && [ "$CLIENT_PATH" = "/complete/path/to/your/backups/" ]; then
+    echo ""
+    echo "You must specify some settings for this feature."
+    echo "Have a look at: /etc/config/autoupdate"
+    echo ""
+    exit 1
+  fi
   scp "$PATH_BAK" "$CLIENT_USER""@$CLIENT_NAME"":$CLIENT_PATH""$TODAY""_$HOSTNAME"".tar.gz"
 }
 
@@ -235,14 +248,6 @@ case $1 in
   fi
 
   if [ $BACKUP = "y" ]; then
-    if [ "$CLIENT_NAME" = "complete-hostname" ] && [ "$CLIENT_USER" = "user" ] && [ "$CLIENT_PATH" = "/complete/path/to/your/backups/" ]; then
-      echo ""
-      echo "You must specify some settings for this feature."
-      echo "Have a look at: /etc/config/autoupdate"
-      echo ""
-      exit 1
-    fi
-
     #backup the current router settings
     do_backup
     remote_backup
