minor adjustments and corrections in code to prepare release - add final key for akira25 - manual-mode: repair control mechanism - manual-mode: remove remote backup function (now own argument) - repair function remote-backup - uci-default-script: repair setting of last_upgrade date - repair create_time_reminder(): preserve time reminder over sysupgrade. - repair syntax error in function set_preserved_backup_dir() - remove double creation of backup file

diff --git a/files/autoupdate b/files/autoupdate
--- a/files/autoupdate
+++ b/files/autoupdate
@@ -91,30 +91,7 @@ case $1 in
 
     #Check for upgrades
     chk_upgr
-
-    #do backup
-    read -p "Do you want to save a backup on your (remote) machine? (y/n): " BACKUP
-
-    if [ $BACKUP != "y" -a $BACKUP != "n" ]; then
-        echo "Error: Input is neither 'y' nor 'n'"
-        until [ $BACKUP = "y" -o $BACKUP = "n" ]; do
-            read -p "Please give a valid value (y/n): " BACKUP
-        done
-    fi
-
-    if [ $BACKUP = "y" ]; then
-        #backup the current router settings
-        create_backup_file
-        remote_backup
-    fi
-
-    if [ $? == 1 ]; then
-        echo ""
-        echo "ERROR: Backup failed. The values given in the config file may be incorrect."
-        echo ""
-        exit 1
-    fi
-
+    #fetch router and tunnel-type
     get_router
     get_type
 
@@ -134,6 +111,10 @@ case $1 in
         echo "Error: Input is neither 'y' nor 'n'"
         until [ "$C" = "y" -o "$C" = "n" ]; do
             read -p "Please give a valid value (y/n): " C
+            if [ "$C" = "n" ]; then
+                echo "Auto recognition failed. Please download the right firmware yourself."
+                exit 1
+            fi
         done
     fi
 
@@ -164,13 +145,12 @@ case $1 in
     echo ""
     echo "Start flashing the image now."
     write_update_date
-	create_time_reminder
+    create_time_reminder
 
     sysupgrade $PATH_BIN
     ;;
 
 -r)
-    do_backup
     remote_backup
     ;;
 
